# Generated by Django 3.2.12 on 2022-04-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_purshaseorder_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('FULFILLED', 'FULFILLED'), ('PENDING', 'PENDING')], default='PENDING', max_length=300),
        ),
    ]
