# Generated by Django 3.2.12 on 2022-04-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='franchise',
            new_name='enterprise',
        ),
        migrations.RenameField(
            model_name='purchaseorderaddresses',
            old_name='franchise',
            new_name='enterprise',
        ),
    ]
