# Generated by Django 3.2.12 on 2022-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220408_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_date',
            field=models.DateTimeField(),
        ),
    ]
