# Generated by Django 3.2.12 on 2022-04-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220408_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='list_price_currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='unit_price_currency',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='list_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
