# Generated by Django 3.2.12 on 2022-06-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220615_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
