# Generated by Django 3.2.12 on 2022-06-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220615_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='total',
            new_name='discount_amount',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subtotal_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
