# Generated by Django 3.2.12 on 2022-06-19 10:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220616_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasesOrderItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('guid', models.UUIDField()),
                ('purchase_order_guid', models.UUIDField()),
                ('code', models.CharField(max_length=300)),
                ('product_name', models.CharField(blank=True, max_length=300, null=True)),
                ('product_description', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity', models.FloatField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('unit_discount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
