# Generated by Django 3.2.12 on 2022-04-09 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('category_name', models.CharField(max_length=300)),
                ('category_code', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-section', '-category_name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('section_name', models.CharField(max_length=250)),
                ('section_type', models.CharField(choices=[('OFFICE', 'OFFICE'), ('SOLAR', 'SOLAR'), ('PHONES', 'PHONES'), ('KITCHEN', 'KITCHEN'), ('LIVING ROOM', 'LIVING ROOM'), ('ACCESSORIES', 'ACCESSORIES')], default='LIVING ROOM', max_length=250)),
                ('section_code', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-section_name'],
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('updated_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField()),
                ('enterprise', models.CharField(max_length=250)),
                ('units_name', models.CharField(max_length=300)),
                ('units_code', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.ManyToManyField(to='debit.Category')),
            ],
            options={
                'ordering': ['-units_name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.section'),
        ),
    ]
